### ISSUE TITLE
Expand what Archivist looks for in the queue to remove old posts

### ISSUE THREAD

**Issue by itsthejoker** [GrafeasGroup/tor_archivist#23]
https://github.com/GrafeasGroup/tor_archivist/blob/main/tor_archivist/main.py#L82

I found out why the archivist misses old posts -- it's because eventually Reddit stops returning posts for a single sorting method (new, hot, controversial). We will need to do this for each available sorting method, every time, in order to get all old posts.

* top
* new
* controversial
* hot

**Comment by MollyMaclachlan** [comment]
If I'm not mistaken this is redundant with #46 and #43 having been closed.

~~sorry just snooping around the repos~~
