### ISSUE TITLE
Old posts (29h+) remaining in queue

### ISSUE THREAD

**Issue by itsthejoker** [GrafeasGroup/tor_archivist#43]
Not all posts are getting removed and it's not entirely clear why. We've deployed one hotfix so far to patch the delay system out but it hasn't seemed to fix it. Things are getting removed, but not enough. There's either something wrong with the Archivist or there's something wrong with the result that it's getting back from Blossom.

**Comment by TimJentzsch** [comment]
Blossom only returns at most 100 posts for the `submission/expired` endpoint. It seems like these are filled up with removed posts that are not archived.

The archivist doesn't change the Blossom object if that happens, so we seem to be "clogged up".
The solution will be to set the archived or removed_from_reddit flag in that situation to remove these posts from the endpoint.
